# Use root/example as user/password credentials
version: '3'

services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run dev"

  db:
    image: postgres:15.2
    container_name: db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: ExampleDB
    volumes:
      - ./DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
